apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.identity.service.name }}
  labels:
{{ include "dex.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.identity.service.type }}
  ports:
    - port: {{ .Values.identity.service.port }}
      {{- with .Values.identity.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "dex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
