---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-template
  namespace: {{ .Release.Namespace }}
data:
  template: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {{ "{{" }}.CAData{{ "}}" }}
{{ if .Values.apiserverURL }}
        server: {{ .Values.apiserverURL }}
{{- else }}
        server: https://{{ .Values.global.clusterDomain }}:6443
{{- end }}
      name: {{ "{{" }}.ClusterName{{ "}}" }}
    contexts:
    - context:
        cluster: {{ "{{" }}.ClusterName{{ "}}" }}
        namespace: {{ "{{" }}.Namespace{{ "}}" }}
        user: {{ "{{" }}.Username{{ "}}" }}
      name: {{ "{{" }}.Username{{ "}}" }}@{{ "{{" }}.ClusterName{{ "}}" }}
    current-context: {{ "{{" }}.Username{{ "}}" }}@{{ "{{" }}.ClusterName{{ "}}" }}
    kind: Config
    preferences: {}
    users:
    - name: {{ "{{" }}.Username{{ "}}" }}
      user:
        token: {{ "{{" }}.Token{{ "}}" }}
