kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: marketplace
rules:
  - apiGroups:
      - marketplace.criticalstack.com
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "events"
      - "secrets"
    verbs:
      - "*"
