kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: marketplace-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: marketplace
subjects:
  - kind: ServiceAccount
    name: marketplace
    namespace: {{ .Release.Namespace }}
