apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: users-editor
rules:
- apiGroups:
  - criticalstack.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - criticalstack.com
  resources:
  - users/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    criticalstack.com/description: |
      Default role for namespace-level admin access. Allows read/write access to most resources in a namespace,
      including the ability to create roles and rolebindings. It does not allow write access to resource quotas, limit
      ranges, or to the namespace itself, nor to clusterroles or clusterrolebindings.
  labels:
    criticalstack.com/rbac: defaults
  name: default-admin
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumes 
  - persistentvolumeclaims
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - serviceaccounts
  - services
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments/rollback
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - "*"
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - deployments/rollback
  verbs:
  - create
  - delete
  - detetecollection
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    criticalstack.com/description: "Default role for read-only access."
  labels:
    criticalstack.com/rbac: defaults
  name: default-audit
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    criticalstack.com/description: |
      Default role for developers. Gives read/write access to most namespace-level resources. It does not allow write
      access to ingresses, resource quotas, and limit ranges, or to cluster-level resources.
  labels:
    criticalstack.com/rbac: defaults
  name: default-developer
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy 
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - serviceaccounts
  - services
  - services/proxy 
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments/rollback
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - deployments/rollback
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - default-cluster-restricted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    criticalstack.com/description: |
      Default role that allows super-user access to perform any action on any resource.
  labels:
    criticalstack.com/rbac: defaults
  name: default-cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
