apiVersion: v1
kind: Service
metadata:
  name: {{ include "criticalstack-ui.fullname" . }}
  labels:
{{ include "criticalstack-ui.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "criticalstack-ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
