apiVersion: v1
kind: Secret
metadata:
  name: criticalstack-ui-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ ( include "criticalstack-ui.gen-session-key" . ) | indent 2 }}
